-- 코드를 입력하세요
SELECT  BOD.TITLE
      , BOD.BOARD_ID
      , REP.REPLY_ID
      , REP.WRITER_ID
      , REP.CONTENTS
      , TO_CHAR(REP.CREATED_DATE,'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD BOD
INNER JOIN USED_GOODS_REPLY REP
        ON BOD.BOARD_ID = REP.BOARD_ID
WHERE 1=1
  AND TO_CHAR(BOD.CREATED_DATE,'YYYY-MM') = '2022-10'
ORDER BY REP.CREATED_DATE, BOD.TITLE
