-- 코드를 입력하세요
SELECT '/home/grep/src/' || BOD.BOARD_ID || '/' || FLE.FILE_ID || FLE.FILE_NAME || FLE.FILE_EXT AS FILE_PATH
FROM USED_GOODS_BOARD BOD
INNER JOIN USED_GOODS_FILE FLE
        ON BOD.BOARD_ID = FLE.BOARD_ID
WHERE 1=1
  AND BOD.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD BOD)
ORDER BY FLE.FILE_ID DESC
